### ISSUE TITLE
Broken on Vuejs2

### ISSUE THREAD

**Issue by Vorror** [FranzSkuffka/vue-medium.js#1]
The example seems broken when using vuejs2
https://jsfiddle.net/jg00ws1j/3/

**Comment by janwirth** [comment]
Hey Vorror,
thank you for reporting this bug.

vue-medium.js is for Vue1 only. Please use https://github.com/FranzSkuffka/vue-medium-editor for Vue2. It is not exactly the same but I hope it still works for you.
